apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: omrade-helse-etterlevelse
  namespace: flex
  labels:
    team: flex
spec:
  pool: nav-dev
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 1
    partitions: 10
    replication: 3
    retentionBytes: -1
    retentionHours: -1
  acl:
    - team: flex
      application: flex-juridisk-vurdering-test-backend
      access: read
    - team: flex
      application: syfosoknad
      access: write
    - team: flex
      application: sykepengesoknad-backend
      access: write
    - team: flex
      application: flex-syketilfelle
      access: write
    - team: teamsykmelding
      application: teamsykmelding-pik
      access: write
    - team: risk
      application: sigmund
      access: write
    - team: tbd
      application: spre-subsumsjon
      access: write
    - team: tbd
      application: spydig
      access: read
