name: "Deploy topic"
on: push

jobs:
  deploy-topic-til-dev:
    if: github.ref_name == 'main' || startsWith(github.ref_name, 'dev-')
    name: Deploy topic til dev-gcp
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy topic til dev-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: topic/dev.yaml

  deploy-topic-til-prod:
    if: github.ref_name == 'main'
    name: Deploy topic til prod-gcp
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy topic til prod-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: topic/prod.yaml
